sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.8.2

before_install:
  - docker-compose build sevenone
  - docker-compose build seventwo

script:
  - docker-compose run sevenone
  - docker-compose run seventwo
