sevenone:
  dockerfile: Dockerfile-71
  extends:
    file: ./docker-compose.base.yml
    service: application
  links:
   - cache
   - redis

seventwo:
  dockerfile: Dockerfile-72
  extends:
    file: ./docker-compose.base.yml
    service: application
  links:
   - cache
   - redis


cache:
  image: behance/docker-memcached
redis:
  image: redis
